src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(?string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->Category;
    }

    public function setCategory(?Categorie $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategorieRepository")
 */
class Categorie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="Category")
     */
    private $articles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId($id): self
    {
        $this->id = $id;
    }


    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getCategory() === $this) {
                $article->setCategory(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/articles", name="articles_index")
     */
    public function index()
    {
        $repo=$this->getDoctrine()->getRepository(Article::class);
        $articles=$repo->findAll();

        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog")
     */
    public function index()
    {
        $articles =["dell","tochiba","hp"];
        return $this -> render('blog/index.html.twig', [ 'art'=>$articles] );
    }
    /**
     * @Route("/articles", name="articles")
     */
    public function lister(){
        $articles =["dell","tochiba","hp"];
        return $this -> render('blog/articles.html.twig', [ 'art'=>$articles] );
    }
}

templates/article/index.html.twig
{#
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/SymApp/src/Controller/ArticleController.php'|file_link(0) }}">src/Controller/ArticleController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/SymApp/templates/article/index.html.twig'|file_link(0) }}">templates/article/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}
#}

{% extends 'base.html.twig' %}

{% block title %}Nos articles{% endblock %}
{% block body %}
   <div class="container">
       <h1>Voici nos articles</h1>
       <table class="table table-hover">
           <thead>
           <tr>
               <th scope="col">Titre</th>
               <th scope="col">Contenu</th>
               <th scope="col">Categorie</th>
           </tr>
           </thead>
           <tbody>

                 {% for article in articles %}
              <tr class="table-primary">
               <td>{{ article.title }}</td>
               <td>{{ article.content }}</td>
               <td>{{ article.category.name }}</td>
              </tr>
                 {% endfor %}

           </tbody>
       </table>
   </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css"/>
        {% block stylesheets %}  {% endblock %}
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ path ('blog') }}">  Symapp </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path ('blog') }}"> Accueil <span class="sr-only">(current)</span></a>
                </li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
<br>


        {% block body %}{% endblock %}
        <script src = "/js/bootstrap.min.js"></script>
        <script src = "/js/jquery.min.js"></script>
        <script src = "/js/popper.min.js"></script>

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/blog/articles.html.twig
{% extends "base.html.twig" %}
{%  block title %} Liste d'articles {% endblock %}
{% block body %}

{#<ul>
    {%for k,p in art%}
        <li>{{ k }}-{{ p }}<br> </li>
    {% endfor %}
</ul>
<a href ="{{ path ('blog') }}">lien</a>
#}

<ul>
    {%for k,p in art%}
        <li>{{ k }}-{{ p }}<br> </li>
    {% endfor %}
</ul>
<a href ="{{ path ('articles') }}">lien</a>
{% endblock %}

templates/blog/index.html.twig
{% extends "base.html.twig" %}

{%  block title %} Liste d'articles {% endblock %}
{% block body %}


        <div class="container">


                <h1 class="display-3"> Bienvenue sur SymApp </h1>
                <p class="lead">Nous mettre a votre disposition une large categorie de produit.</p>
                <hr class="my-4">
                <p>Vous etes curieux !!</p>
                <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{{ path ('articles') }}" role="button">VOIRE NOS PRODUITS. </a>
                </p>

        </div>
        <div class = "jumbotron mt-3">
        </div>

{% endblock %}